version: '3'
services:
  evaluation:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: $HOME/data/
        target: /src/data
    environment:
      - privacy-model=blabla
