# set base image (host OS)
FROM python:3.6.9-slim-buster

#Local dependencies for cv2
RUN apt-get update
RUN apt-get install build-essential python3-dev pkg-config wget -y
RUN apt-get install -y \
    libavformat-dev libavcodec-dev libavdevice-dev \
    libavutil-dev libswscale-dev libswresample-dev libavfilter-dev
RUN wget https://nvidia.box.com/shared/static/49fzcqa1g4oblwxr3ikmuvhuaprqyxb7.whl -O onnxruntime_gpu-1.6.0-cp36-cp36m-linux_aarch64.whl

# set the working directory in the container
WORKDIR /src/

# copy the content of the local directory to the working directory
COPY requirements369.txt /src/
COPY sfu_server /src/
COPY model /src/
COPY detector /src/
COPY video_data /video_data/
COPY data /data/

# install dependencies
RUN pip install --upgrade pip setuptools wheel
# RUN pip install ../onnxruntime_gpu-1.6.0-cp36-cp36m-linux_aarch64.whl
RUN pip install -r requirements369.txt

# command to run on container start
CMD [ "python", "./main.py" ]