# set base image (host OS)
FROM python:3.8-slim-buster

#Local dependencies for cv2
RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6 wget -y
RUN apt-get install gcc python3-dev -y
RUN wget https://nvidia.box.com/shared/static/v59xkrnvederwewo2f1jtv6yurl92xso.whl -O onnxruntime_gpu-1.12.1-cp38-cp38-linux_aarch64.whl

# set the working directory in the container
WORKDIR /src/

# copy the content of the local directory to the working directory
COPY requirements369.txt /src/
COPY sfu_server /src/
COPY model /src/
COPY detector /src/
COPY video_data /video_data/
COPY data /data/

# install dependencies
# what if any of these packages are not made for arm64???
RUN pip3 install --upgrade pip setuptools wheel
RUN pip3 install ../onnxruntime_gpu-1.12.1-cp38-cp38-linux_aarch64.whl
RUN pip3 install -r requirements369.txt --verbose

# command to run on container start
CMD [ "python", "./main.py" ]